# Generated by Django 6.0.1 on 2026-02-14 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boat",
            options={"ordering": ["-club_owner", "category"]},
        ),
        migrations.RemoveField(
            model_name="boat",
            name="owner",
        ),
        migrations.AddField(
            model_name="boat",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="boats_owned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
