# Generated by Django 6.0.1 on 2026-02-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0002_alter_boat_options_remove_boat_owner_boat_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="boat",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="boats/"),
        ),
    ]
