# Generated by Django 6.0.1 on 2026-03-06 16:09

import club.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0003_boat_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=club.models.user_upload_dir
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="phone_visibility",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_participant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="worktask",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_participant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
