# Generated by Django 6.0.1 on 2026-03-10 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0004_member_avatar_member_phone_visibility_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={
                "ordering": ["last_name", "first_name"],
                "permissions": [("active_member", "Member is active")],
                "verbose_name": "member",
                "verbose_name_plural": "members",
            },
        ),
    ]
